trigger:
- master
pool:
  vmImage: 'ubuntu-latest'
jobs:
  -job: Teste
  steps:
    - task: Bash@3
      displayName: 'Dependencias'
      inputs:
        targetType: 'inline'
        script: 'npm install'
    - task: Bash@3
      displayName: 'Lint'
      inputs:
        targetType: 'inline'
        script: 'npm run lint'
  -job: ParallelTesting
  strategy:
    parallel: 2
  steps:
    - task: Bash@3
      displayName: 'Teste Unitario'
      inputs:
        targetType: 'inline'
        script: 'npm run test'
