trigger:
- master
#include:
#-master
#-release
#-feature/*
#exclude:
#-releases/old*
#-feature/*-working
pool:
  vmImage: 'ubuntu-latest'
#jobs:
#-job: A
#   steps:
#   - bash: Echo "A"
#-job: B
#   steps:
#   -bash: Echo "B"
steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'