trigger:
- master
#include:
#-master
#-release
#-feature/*
#exclude:
#-releases/old*
#-feature/*-working
pool:
  vmImage: 'ubuntu-latest'
#jobs:
#-job: A
#   steps:
#   - bash: Echo "A"
#-job: B
#   steps:
#   -bash: Echo "B"
steps:
- task: Bash@3
  displayName: 'Dependencias'
  inputs:
    targetType: 'inline'
    script: 'npm install'